version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./reactApp:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "cd react-todo && yarn install && yarn start"
    ports:
      - "3000:3000"
      - "5001:5000"