version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reactApp:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "cd react-todo && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true 